# Generated by Django 3.1.4 on 2021-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_longtoshort_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtoshort',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='longtoshort',
            name='longurl',
            field=models.URLField(),
        ),
    ]
